### ISSUE TITLE
What should be the default behaviour for decoding invalid entities

### ISSUE THREAD

**Issue by jakubpawlowicz** [YorickPeterse/oga#118]
We recently stumbled upon an issue with parsing the following entities:

```ruby
Oga.parse_xml("<a>&#TAB;</a>")
```
which results in
```
ArgumentError: invalid value for Integer(): "TAB"
	from /app/lib/oga/xml/entities.rb:93:in `Integer'
	from /app/lib/oga/xml/entities.rb:93:in `block in decode'
	from /app/lib/oga/xml/entities.rb:92:in `gsub'
	from /app/lib/oga/xml/entities.rb:92:in `decode'
```

The ```Oga.parse_xml("<a>&#x;</a>")``` results in the same exception being raised.

I wonder if Oga could rather leave these entities as they are if they cannot be decoded instead of raising an unrecoverable error?

**Comment by jakubpawlowicz** [comment]
Btw, happy to send a PR if you think it's a good idea.

**Comment by YorickPeterse** [comment]
In case of an unrecognised entity Oga is supposed to just leave it as-is. The usage of `Integer()` was initially added to allow specifying the base, but `Object#to_i` can do this as well. The code would have to be changed so that the process is as following:

1. Try to convert to a number, return nil or something similar upon a failure (instead of raising an error)
2. If converted, convert to a set of codepoints, otherwise leave the entity as is

I'm not sure if there's a way to tell `String#gsub` with a block to _not_ replace a value. Returning the matched value as-is is probably the only option.

> Btw, happy to send a PR if you think it's a good idea.

PRs are always welcome :)

**Comment by jakubpawlowicz** [comment]
Great, I'll come back with some code :+1:
