### ISSUE TITLE
Problem parsing HTML <object> tag

### ISSUE THREAD

**Issue by jakubpawlowicz** [YorickPeterse/oga#129]
We stumbled upon an issue with parsing HTML <object> tag.
If the <object> tag has enclosed  <param> tags then the closing </object> tag will be placed in the wrong position, possibly due to a wrong parsed tree?

```ruby
$ source = <<-HTML
<object>
  <param></param>
  <param></param>
</object>
HTML
=> "<object>\n  <param></param>\n  <param></param>\n</object>\n"
$ Oga.parse_html(source).to_xml
=> "<object>\n  <param /></object>\n  <param />\n\n"
```

Do you have an idea why it happens? We'll be happy to submit a patch if you can pinpoint the place it happens at.

**Comment by YorickPeterse** [comment]
The specific HTML is invalid as `param` tags can not have any content, thus they're supposed to be closed using `<param />` and not `</param>`. The moment Oga sees a `<param>` tag it automatically injects a closing `</param>` tag to keep the parser happy, in this case this leads to duplicate closing tags.

To work around this probably https://github.com/YorickPeterse/oga/blob/5d0e8c99af86dab9f4d1840f37625bf6b964c379/lib/oga/xml/lexer.rb#L515 has to be changed so that it only emits `T_ELEM_END` when the closing tag name matches the currently enclosing element. This _might_ break other tests but I haven't verified this.

**Comment by jakubpawlowicz** [comment]
Ah, it makes sense. Unfortunately the `<param></param>` is so common...
Let's see if the change you suggested breaks other tests!
