### ISSUE TITLE
Provide a mechanism for extending/decorating nodes attached to a particular document

### ISSUE THREAD

**Issue by jbr** [YorickPeterse/oga#146]
Nokogiri provides a mechanism for adding behavior to all nodes on a given document tree. [Loofah](https://github.com/flavorjones/loofah) is built on this extension point. In order to directly port Loofah to Oga (flavorjones/loofah#100), Oga will need to add a comparable API.  Depending on how large an API you want to support, this could take the form of:

* a `Document#node_attached(node)` callback which just returns `node` by default
* some sort of node middleware pattern, where things that respond to `call` get pushed into an array (see bottom of [this](https://blog.jbr.me/a-brief-tour-of-nokogiri-decorators#maybe-we-can-understand-this-as-a-special-type-of-middleware:a593262b97a8f3ec1e2657c7b6ab1472) for a sketch)
* a direct implementation of Nokogiri's decorators API (which doesn't actually meet Loofah's need incredibly well)

I'm happy to PR any of the above.

**Comment by YorickPeterse** [comment]
Right now the classes to use for building document trees are all hard-coded, for example: https://github.com/YorickPeterse/oga/blob/40501f95224998e243b72dd855c65eada8fd2bd4/lib/oga/xml/parser.rll#L362

What I'm thinking of is setting these classes as instance variables in `initialize` and using those variables instead. This way if somebody wants to use a custom class they'd just use the following code:

```ruby
class MyElement < Oga::XML::Element
end

class MyParser < Oga::XML::Parser
  def initialize(*args)
    super

    @element_class = MyElement
  end
end
```

This removes the need for calling `Object#extend` during runtime, though you'd have to make sure the arguments passed to `initialize` are also passed to the parent class.

I'm not a fan of using methods for this as the overhead of having to call an extra method can be quite significant especially for larger XML/HTML documents.

**Comment by jbr** [comment]
Yeah, I was concerned about the overhead of method calls, was planning on benchmarking. As it is, loofah has more overhead from this extension pattern than I would have expected. Dependency injection (providing a custom class) seems like a good solution to the problem, except for the fact that there is a whole class hierarchy involved.

Here's my concern about classes as instance variables: If Loofah wants to extend a class in the middle of the class hierarchy, they'll need to subclass all descendant classes as well, which might entail a lot of boilerplate. If we want to add a method to all `Node` (or subclass of `Node`) instances, wouldn't they have to provide a custom subclass of `Element`, `Node`, `CharacterNode`, `TextNode`, `Cdata`, `ProcessingInstruction`, `Comment`, etc?

```ruby
class MyElement < Oga::XML::Element
  include MyParser::SpecialNodeBehavior
end
class MyCharacterNode < Oga::XML::CharacterNode
  include MyParser::SpecialNodeBehavior
end
#…etc, for each of the classes
class MyParser < Oga::XML::Parser
  def initialize
    super
    @element_class = MyElement
    @character_node_class = MyCharacterNode
    #… etc, for each of the necessary Node subclasses
  end
end
```

**Comment by YorickPeterse** [comment]
> If we want to add a method to all Node (or subclass of Node) instances, wouldn't they have to provide a custom subclass of Element, Node, CharacterNode, TextNode, Cdata, ProcessingInstruction, Comment, etc?

If code wants to extend all classes then yes, they'd have to define custom classes for every type. I don't think there's a way around this without monkey patching classes globally, which in turn might break code.

**Comment by jbr** [comment]
Had another chance to look at this.  I think there might be a way for Loofah to get away with subclassing `Oga::XML::Parser` and overriding each of the `on_…` methods without any changes to oga.  Is that a stable API / safe to build on? Additionally, loofah would need to override `Document#children` and `Document#children=` to return Loofah's NodeSet.  Do you prefer the ivar approach?

**Comment by YorickPeterse** [comment]
> Had another chance to look at this. I think there might be a way for Loofah to get away with subclassing Oga::XML::Parser and overriding each of the on_… methods with only minimal changes to oga. Is that a stable API / safe to build on?

No, you'd have to basically re-implement all the `on_` methods just to get a different type of object returned. 

> Additionally, loofah would need to override Document#children and Document#children= to return Loofah's NodeSet

Loofah needing a custom NodeSet class is quite problematic since this also means having to somehow extend the following classes to allow for custom NodeSet classes:

* `Oga::XML::Document`
* `Oga::XML::Node`
* `Oga::XML::Element`
* basically any other piece of code that creates a NodeSet

I fear that providing the means for this is going to add complexity the vast majority of users out there won't use. 

For what reason exactly does Loofah need to extend all these classes? Are the methods it adds somehow exposed to users, or are they for internal purposes only?

**Comment by jbr** [comment]
My guess is that this nokogiri api existed for extending document tree members, so loofah was built around it.  It's just a convenience entry-point though, since it's not used for traversal.  However, the single method added onto `Node`s (and subclasses), `NodeSet`s, and `Document`s (`#scrub!`) is part of the public api and I'd be very surprised if Loofah's maintainers would be amenable to making that large a breaking change.  Without support for extending tree members, the best way to move rails from nokogiri to oga might actually be replacing Loofah with a sanitizer that is less tightly coupled to the underlying xml parser.  This would obviously be a significantly larger undertaking.

I think there's a way oga could support some sort of decoration mechanism without adding more overhead than an instance variable check for users that don't it.

```ruby
  def on_text(text)
    node = Text.new(:text => text)
    if @parser_decorator
      @parser_decorator.call(node)
    else
      node
    end
  end

  def on_element(namespace, name, attributes = {})
    element = Element.new(
      :namespace_name => namespace,
      :name           => name,
      :attributes     => attributes
    )

    if @parser_decorator
      @parser_decorator.call(element)
    else
      element
    end
  end
```

Etc. Any slow extension would happen inside of `@parser_decorator` and would only impact loofah (which is already absorbing the cost of nokogiri's decorators).

**Comment by YorickPeterse** [comment]
So thinking of this there's one big problem: supporting this outside of the parser. For example, in Oga you can manually add nodes to a DOM tree as follows:

    element = Oga::XML::Element.new(name: 'foo')
    some_other_element.children << element

If we were to use decorators we'd now end up pushing a vanilla Element into the DOM. Of course we can use our own class directly but there are other cases where we can't. For example, setting an attribute creates an `Oga::XML::Attribute` meaning that if we were to use decorators we'd now create a vanilla Attribute instead of our decorator. I'm really not a fan of attaching decorator information to an `Oga::XML::Document` and then making sure _every_ method that can possibly create an instance of one of the classes in `Oga::XML` uses any corresponding decorator classes. This is going to get super buggy and I doubt anybody (besides Loofah) would actually need it.

Considering switching to Oga is probably going to be backwards incompatible anyway it might be worth considering changing the Loofah API to not rely upon using decorators, though I do not the impact of such a change.

**Comment by YorickPeterse** [comment]
I'm going to close this. While implementing a decorator-like system on parser level is doable (even though I'm not a fan of this) adding it to the various other `Oga::XML` classes adds unnecessary complexity. To support this every class' `initialize` method would need an optional argument that can be used to pass some kind of configuration object. This configuration object in turn would dictate what classes to use for certain operations. It leads to overly complex code and it's too easy to make mistakes in this setup.

For Loofah I'd recommend an API in which they don't patch any classes, instead using something like `Loofah.scrub(document, ...)` instead of `document.scrub`. I don't see Oga being able to provide a reasonable alternative that doesn't turn into a maintenance/code nightmare.

**Comment by jbr** [comment]
I think this makes sense.  Loofah's API is fairly inextricably linked to nokogiri, and even consumers of Loofah have to interact with raw nokogiri objects, so there would be no easy migration path.  My guess is that the path forward would be to take rails-html-sanitizer and Loofah's tests and write a new sanitizer based on oga.  I'd be willing to work towards this goal, but it's a large undertaking.  Is oga fast enough and full-featured enough currently for this to be possible/feasible?

**Comment by YorickPeterse** [comment]
>  Is oga fast enough and full-featured enough currently for this to be possible/feasible?

Can't tell for certain, this depends on how fast it would need to be. Is it going to be slower than Nokogiri? Maybe. Does that actually matter? Who knows.
