### ISSUE TITLE
Oga causing MultiXML tests to fail with Errno::ESPIPE: Illegal seek

### ISSUE THREAD

**Issue by sferik** [YorickPeterse/oga#153]
See https://travis-ci.org/sferik/multi_xml.

Any idea what’s causing this error?

Here is the relevant spec:

```ruby
context 'a duplexed stream' do
  before do
    @xml, wr = IO.pipe

    Thread.new do
      '<user/>'.each_char do |chunk|
        wr << chunk
      end
      wr.close
    end
  end

  it 'parses correctly' do
    expect(MultiXml.parse(@xml)).to eq('user' => nil)
  end
end
```

**Comment by YorickPeterse** [comment]
@sferik: When a lexer is initialized and the input object responds to `rewind` this method is called on the input object: https://github.com/YorickPeterse/oga/blob/00ab8bbe73e6c28921fa9ac0c3e54eddfcecd20c/lib/oga/xml/lexer.rb#L126

Apparently pipes respond to this method but don't support it. Having looked at the IO class there doesn't seem to be a way of checking if an IO objects supports `seek` or not. 

The only solution that I can think of is to _not_ have a Lexer instance reset its internal state after it has finished running. Since Lexer instances aren't re-used at the moment this shouldn't really impact users, though having an instance you can only use once feels a bit dirty.

**Comment by sferik** [comment]
> The only solution that I can think of is to *not* have a Lexer instance reset its internal state after it has finished running. Since Lexer instances aren't re-used at the moment this shouldn't really impact users, though having an instance you can only use once feels a bit dirty.

This solution sounds good to me. A user could still manually reset a Lexer instance if they want to reuse it, right? Would you accept a pull request that makes this change?

**Comment by YorickPeterse** [comment]
@sferik I think it's easier to just _not_ support resetting in any way. For one the API is private so one shouldn't use it directly, second I'm not a fan of saying "You can call `reset` but _not_ when using a pipe, socket, etc"; instead it rather just not have any resetting.

> Would you accept a pull request that makes this change

Yes.
