### ISSUE TITLE
to_xml on element where children are appended does not work in 2.4+ releases 

### ISSUE THREAD

**Issue by john7doe** [YorickPeterse/oga#160]
The following spec work on (at least) 2.2 and 2.3, but fails on later releases 

(in element_spec.rb)

```
 describe '#to_xml' do
    ...
    it 'includes the child nodes if appended' do
      instance = described_class.new(
        :name     => 'p',
        :children => [Oga::XML::Comment.new(:text => 'to_xml')]
      )

      instance.children += [Oga::XML::Comment.new(:text => 'is working')]

      instance.to_xml.should == '<p><!--to_xml--><!--is working--></p>'
    end
   ...
end

```

**Comment by YorickPeterse** [comment]
Seems the `next` pointer for the first text node isn't set properly. Probably `NodeSet#+` doesn't properly update `previous` / `next`.

**Comment by YorickPeterse** [comment]
Ah, `NodeSet#+` doesn't pass along the owner to the new `NodeSet`, that explains why `previous` / `next` aren't updated.

**Comment by YorickPeterse** [comment]
@john7doe Ah, it looks like this was more or less expected behaviour. From the [documentation of `NodeSet#+`](http://code.yorickpeterse.com/oga/latest/Oga/XML/NodeSet.html#%2B-instance_method):

> Creates a new set based on the current and the specified set. The newly created set does not inherit ownership rules of the current set.

This also affects `+=` since `X += Y` is just syntax sugar for `X = X + Y`.

Thinking of it I don't think there's any sane solution for this either. `NodeSet#+` could inherit the owner from the receiving `NodeSet` but this may break code. For example:

```ruby
set1 = NodeSet.new(..., some_owner)
set2 = NodeSet.new(...)
set3 = set1 + set2
```

Here the owner of `set3` would be the same owner as `set1`, but the nodes in both these sets would have their next/previous pointers set based on the owner of `set3`. This could lead to equally confusing behaviour.

Fortunately there are two ways you can work around this:

1. Use [`NodeSet#concat`](http://code.yorickpeterse.com/oga/latest/Oga/XML/NodeSet.html#concat-instance_method)
2. Use [`NodeSet#push`](http://code.yorickpeterse.com/oga/latest/Oga/XML/NodeSet.html#push-instance_method)

Because of the above I don't feel comfortable changing `NodeSet#+`.
