### ISSUE TITLE
Children of nodes

### ISSUE THREAD

**Issue by Seikitsu** [YorickPeterse/oga#175]
Hi, I have problem parsing xml document created from xlsx spreadsheet. I am using PullParser and using something like "node.is_a?(Oga::XML::Element) && node.name == 'row'" to determine row elements, but it has no children element (which it does/shows when doing same thing in nokogiri). Also, I attempted to just write text value from each cell (simply node.text), but it only shows some integers. File should be fine, with nokogiri (similiar code) is working, I want to use/try Oga because I suspect memory leaking / inefficiency in nokogiri and I need to process xlsx spreadsheets with sheets with 50K+ rows.
My code looks like:
      handle = File.open(path,'rb')
      parser = Oga::XML::PullParser.new(handle)
      parser.parse do |node|
        next unless node.is_a?(Oga::XML::Element) && node.name == 'row'
        puts node.children.empty?
      end

Is this a bug? Or am I doing something wrong? Advice much appreciated!

**Comment by YorickPeterse** [comment]
@Seikitsu When you use the pull parsing API you can not request the child nodes of the current element (doing so will produce an empty NodeSet). This is because when you reach a certain node the parser hasn't processed the child nodes yet (the parser works from top to bottom/outer to inner).

I suspect that Nokogiri has special code where calling `children` on an element will automatically advance the parser and produce a partial DOM tree. Oga has no such API, and I don't have any plans on adding it either as objects such as `Oga::XML::Element` are completely detached from the parser.

If you need to process certain elements only if they're a child of another, what you'd typically do is set some sort of flag when entering said element, then reset it when you're done. This is easier to do when using the SAX API as this API allows you to run code when both entering and leaving elements. See http://code.yorickpeterse.com/oga/latest/Oga/XML/SaxParser.html for more information.

I'll close this since this issue isn't a bug.
