### ISSUE TITLE
Failure to parse consecutive predicates

### ISSUE THREAD

**Issue by badeball** [YorickPeterse/oga#177]
Hi, Yorick

How are you doing?

I think I've found a bug in your application. See the following output.

```
irb(main):012:0> Oga::XPath::Parser.new("//foo[2][2]").parse
LL::ParserError: Received T_INT but there's nothing left to parse
	from /home/jonas/.gem/ruby/2.3.3/gems/ruby-ll-2.1.2/lib/ll/driver.rb:15:in `parser_error'
	from /home/jonas/.gem/ruby/2.3.3/gems/oga-2.10/lib/oga/xpath/parser.rb:280:in `block in each_token'
	from /home/jonas/.gem/ruby/2.3.3/gems/oga-2.10/lib/oga/xpath/lexer.rb:2557:in `add_token'
	from /home/jonas/.gem/ruby/2.3.3/gems/oga-2.10/lib/oga/xpath/lexer.rb:2193:in `advance'
	from /home/jonas/.gem/ruby/2.3.3/gems/oga-2.10/lib/oga/xpath/parser.rb:277:in `each_token'
	from (irb):12:in `parse'
	from (irb):12
	from /home/jonas/.rubies/ruby-2.3.3/bin/irb:11:in `<main>'
```

It's maybe easy to think that consecutive predicates are really just boolean conditions that are AND-ed together, but they're not. Consider the above mentioned query. It is not equivalent to `//foo[position() = 2 and position() = 2]`. It actually selects the 2. foo that is the 2. child of its parent.

**Comment by badeball** [comment]
For reference, the reason why I came across this was to solve the following case. I want to select a `StsRsnInf` if it directly follows a `GrpSts`. Normally, I would write such query as follows.

```
//GrpSts/following-sibling::*[1][self::StsRsnInf]
```

I've currently solved it with the following query.

```xpath
//GrpSts/following-sibling::*[position() = 1 and local-name() = 'StsRsnInf']
```

**Comment by YorickPeterse** [comment]
I took a brief look at the XPath parser and the problem is that in a few places it uses the rule `predicate?` (which means 0 or 1 predicates) instead of `predicate*` (0 or more). I however couldn't quite get this to work in the short amount of time I had available.

Basically I think the following needs to be changed:

* Instances of `predicate?` have to be changed to `predicate*`
* If no predicates were specified then `predicate*` should return an empty array (I think right now it returns `nil` in that case)
* Instead of `if predicate node = s(:predicate, ...) end` code should just be `predicate.each { |n| node = s(:predicate, node, n) }` or something along those lines
* Tests have to be added of course

I myself am quite busy so I have no idea if/when I could get to doing this.

**Comment by badeball** [comment]
I briefly looked at the code back there, but couldn't immediately figure it out. I think I will attempt to take another stab at it. Anyways, there's no hurry here, as I have a workaround.

**Comment by YorickPeterse** [comment]
This has been moved to https://gitlab.com/yorickpeterse/oga/issues/177
