### ISSUE TITLE
Querying NodeSets

### ISSUE THREAD

**Issue by zumoshi** [YorickPeterse/oga#181]
Hello,

I looked at the docs but couldn't find any way to query a NodeSet (result of another query)
```ruby
#this works:
document.css('div span')
#this doesn't:
document.css('div').css('span')
```

the idea is similar to how you can [do this](https://jsfiddle.net/xjj2dtkt/) in jquery:
```js
$('div').find('span')
```

also:
```ruby
#this works
document.css('div.x')
#this doesn't
docuemnt.css('div').css('.x')
```

again the idea is similar to [this](https://jsfiddle.net/xjj2dtkt/1/) is jquery:
```js
$('div').filter('.x')
```
I'm sorry if this is already implanted but I missed it.

otherwise how hard would implanting this be?

for `find` we should be able to loop through all elements and query within each one and merge the results, and for `filter` it should be possible to put all the nodes inside a temporary Element and query within that.

**Comment by YorickPeterse** [comment]
This is currently not supported, and truth be told I don't find it super useful either since you can just do:

```ruby
doc.css('div span')
```

Instead of `doc.css('div').css('span')`

There are also some technical difficulties. A NodeSet can contain different types of objects, some of which can be queried using `#css` / `#xpath` (e.g. `Element`), some of which can't (e.g. Text). Having NodeSet deal with all of this would lead to overly complex code. One option would be to add `#css` / `#xpath` to all classes and return empty values. However, it just doesn't make sense to provide a `css` method to a text node since there's nothing to query.

Could you perhaps explain the specific problem you're trying to solve with this particular feature, and can't that be solved by using the above example?

**Comment by zumoshi** [comment]
I'm porting some jquery based web scraper code to ruby where those functions (or ones such as `.prevAll`) are used, I believe I can simulate most of the other ones if I have `find` and `filter`.

but the general idea is a multi-level search inside the page, imagine you have multiple sections on each page, where each of them has multiple tables, and each table has multiple rows.

perhaps [an example](https://jsfiddle.net/629nyoc4/) can help explain it better. the fiddle is a simple recreation of one of the codes I'm porting. basically, each level adds some meta data, so I can't get all of the rows with one selector because I need to distinguish them based on where they were.

**Comment by YorickPeterse** [comment]
@zumoshi Looking at your example I don't see a particular good reason for extending NodeSet. In the JS code you're probably doing this because a single element doesn't have the jQuery methods, thus you have to do something like `$(t)`. In Oga you can just do something like this:

```ruby
document.css('div').each do |div|
  div.css('p').each do |paragraph|
    # etc
  end
end
```

**Comment by zumoshi** [comment]
perhaps not for the `find` method, since yesterday I've been working on a wrapper class that allows me to simulate jquery methods without needing to make any changes to `oga` itself, I have managed to simulate the original behavior this way:
```ruby
  def find(selector, n)
    if n.is_a? Oga::XML::NodeSet
      x = []
      n.each do |e|
        x += find(selector, e)
      end
      x
    elsif n.is_a? Oga::XML::Document
      n.css(selector)
    elsif n.is_a? Oga::XML::Element
      n.css(selector)
    elsif n.is_a? Oga::XML::Text
      nil
    else
      raise 'Invalid argument'
    end
  end
```
(the original method lacks the `n` parameter and returns a new instance of the wrapper class to allow for a fluent API)

but I still have no idea how to implant `filter`, in the example (line 5 of js), I have used `.prevAll` to get the matching `h4` for each table. for now, I have implanted it as:
```ruby
  def prev(selector)
    x = @n.xpath './preceding-sibling::'+selector
    self.class.new x[0]
  end
```
it works for `h4` as a query because it's the same in css and xpath, but for a more complex query, I would like to be able to do something like this:
```ruby
def prev(selector)
  x = @n.xpath './preceding-sibling::*'
  x.filter(selector) # or x.css(selector), it should work with any css3 query
end
```
which wouldn't work because `x` is a `NodeSet`, also my `find` method won't work here because it will only match children of nodes in the `NodeSet`, not the nodes themselves.

---

side question: would you be interested to accept pull requests for jquery selectors not in css? (e.g. [:has](https://api.jquery.com/has-selector/)). I have implanted a very [basic version](https://github.com/zumoshi/oga/commit/5c9627f6fc20ad1cc5aec56b852164eff2bdff79) (still needs some polishing but it works for simple cases). [:eq](https://api.jquery.com/eq-selector/) and [:contains](https://api.jquery.com/contains-selector/) are next on my list.

**Comment by YorickPeterse** [comment]
@zumoshi I have a bit of a hard time understanding your reply, and I still don't quite understand the usecase (perhaps because of that). Either way, querying should be done from a document or element, not from a NodeSet (at least in Oga itself).

> side question: would you be interested to accept pull requests for jquery selectors not in css?

Oga only implements the CSS selectors described in http://www.w3.org/TR/css3-selectors/ because these are well specified and most commonly available in other libraries. I feel a bit conflicted about adding additional selectors. On one hand they can be useful, on the other hand you might as well use XPath as it's far more powerful and can do all of this out of the box.

**Comment by YorickPeterse** [comment]
Regarding NodeSet, I don't want any querying methods there for the foreseeable future. As explained in https://github.com/YorickPeterse/oga/issues/181#issuecomment-328293433 this would require code to deal with all the different node types when querying and I don't want to have such code in Oga (it's complex enough already).
