### ISSUE TITLE
Support for multi_xml

### ISSUE THREAD

**Issue by YorickPeterse** [YorickPeterse/oga#72]
multi_xml should support for Oga, most likely by using the SAX API of Oga. This will allow me to use v2 of the aws-sdk without having to rely on Nokogiri, or worse: REXML.

**Comment by trevorrowe** [comment]
@YorickPeterse I recently removed the dependency on `multi_xml` from v2 of the `aws-sdk` gem. It has been replaced with a sax/stack XML parser. It currently supports Ox, LibXML, and Nokogiri, with a REXML fallback.

I removed multi_xml primarily for performance. XML responses are now parsed in a single pass, instead of parsing them into a document-like hash and then having to pass over the hash to generate response structures. Additionally, I ran into a small number of differences in the output of mult_xml from the different backends.

I'd love to add support for Oga. I saw on your README that you support sax parsing. For reference, here are the current engines supported by the SDK:

https://github.com/aws/aws-sdk-ruby/tree/master/aws-sdk-core/lib/aws-sdk-core/xml/parser/engines

The actual implementation tend to be very small, here is REXML's:

https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/lib/aws-sdk-core/xml/parser/engines/rexml.rb

I just found the project, and was poking at the issues and saw this so I though I should comment.

**Comment by trevorrowe** [comment]
@YorickPeterse I spent a few minutes working on adding Oga support. With very little code, I've got everything work except for errors. I can't seem to get the `Oga.sax_parse_xml` to emit errors for invalid XML. Looking at the xml parser docs here: http://code.yorickpeterse.com/oga/latest/frames.html#!file.README.html

The only hook I see is the `#parser_error` method and I haven't been able to trigger it.  Thoughts?

**Comment by YorickPeterse** [comment]
> The only hook I see is the #parser_error method and I haven't been able to trigger it. Thoughts?

This particular method is more meant for parser authors to either enhance error messages or add custom handling of errors. For example, https://github.com/YorickPeterse/oga/blob/098cd51ab730721c19bb4d7d172e3c203901a062/lib/oga/xml/parser.rll#L279-L295 is used to add some extra text to error messages to indicate what kind of data caused the error.

Currently Oga's XML lexer is pretty lax and makes sure that most input can be processed. However, you can break it by using for example input such as this:

    Oga.parse_xml('<!--') # => LL::ParserError: Unexpected end of input, expected T_COMMENT_END instead on line 1

Does the AWS SDK actually require the parser to raise errors for invalid XML? In most cases one probably doesn't want to bother with this, hence Oga tries to parse as much as possible by default. Seeing how this is now the potential 3rd request for a "strict" option I can look into adding this if needed.

**Comment by trevorrowe** [comment]
Currently it requires strict validation of the XML, this helps ensure the response body was not truncated. This is necessary as many services use chunked transfer encodings in the response and do not specify how many bytes to expect.

A strict mode would be useful, and maybe would have been a good default mode when working with XML. I can probably work around this currently by simply ensuring that every opened element is closed in the correct order when handling the SAX events.

**Comment by YorickPeterse** [comment]
> A strict mode would be useful, and maybe would have been a good default mode when working with XML

I'll see if I can implement this, it won't be the default though as that would break compatibility with the exisitng 1.x releases, I can also imagine most would _want_ it to be lax by default. Either way, once present I envision you can use this along the lines of `Oga.sax_parse_xml(handler, xml, :strict => true)` or maybe `Oga.sax_parse_xml!(handler, xml)`.

**Comment by YorickPeterse** [comment]
Tracking the strict parsing request in https://github.com/YorickPeterse/oga/issues/107.

**Comment by YorickPeterse** [comment]
multi_xml pull request: https://github.com/sferik/multi_xml/pull/47

**Comment by YorickPeterse** [comment]
Closing this in favour of the multi_xml pull request mentioned above.
