### ISSUE TITLE
Equality opperator for documents

### ISSUE THREAD

**Issue by ImaginateWayne** [YorickPeterse/oga#77]
I have noticed that when I parse xml for two identical documents and then compare them using the '==' operator the result return is false.
```ruby
first = Oga.parse_xml('<xml\>')
second =  Oga.parse_xml('<xml\>')

first == second #returns false
```

I would expect that this example would return true.  

Is this a bug? I'm happy to take a look at it and supply a pull request.

**Comment by YorickPeterse** [comment]
This isn't really a bug, just a lack of a possible feature. Classes such as `Oga::XML::Document` and `Oga::XML::Element` don't define their own `==` methods, thus they use the default ones provided by `Object`.

The tricky thing is that for two documents to be the same they both must have:

* The exact same XML declaration
* The exact same doctype
* The exact same nodes (text, elements, etc)

For elements two elements must have the following in common:

* The same name
* The same namespace
* The same attributes
* The same child nodes

To get all this done the `==` operators would one way or another recurse into the child nodes of their containers, compare those, recurse further, compare, etc. This would make `==` quite a heavy operation, so I'm not really sure if it's worth implementing this.

**Comment by ImaginateWayne** [comment]
Thanks for the detailed response, it looks like you have put a lot of thought into it already, and if I'm honest I only wanted to make use of the equals operator for my rspec tests to make sure my document is getting parsed through a multi-parser method I've written...

In the spirit of solving problems because it's fun, I started thinking that equality through node comparison only becomes expensive in a large document with many nodes when the documents are actually equal because you could return false during the recursive comparison as soon as an element or structure (node count) is found to be unequal.

After wondering how many people would do the whole document comparisons and coming to the conclusion that it's an unlikely uses case,  I discovered a way to cheat for my purposes and that's to use the ```.to_xml``` method which seems to print the document out as a string.

Is there any reason the ```.to_s``` method doesn't do this? 

Regardless a ```.to_s``` method could be an easy way to get basic comparison though it has it's short comings also.

Let me know if you would like me to take a look at it?

**Comment by YorickPeterse** [comment]
Using `to_xml` is an option for the time being, and I can alias `to_s` to it in the future if needed. I'll give adding custom `==` operators some thought because relying on `to_xml` is a bit of a hack for this.

**Comment by YorickPeterse** [comment]
I'm scrapping this, for it could introduce serious bugs. To clarify, for this to
work I'd have to define a custom `==` method on most classes in the `Oga::XML`
namespace such as `XML::Text`, `XML::Attribute`, etc. This would allow you to do
the following:

    text1 = Oga::XML::Text.new(:text => 'foo')
    text2 = Oga::XML::Text.new(:text => 'foo')

    text1 == text2 # => true

This becomes problematic when we add these instances to a NodeSet:

    text1 = Oga::XML::Text.new(:text => 'foo')
    text2 = Oga::XML::Text.new(:text => 'foo')
    set   = Oga::XML::NodeSet.new([text2, text2])

If we now request the indexes of `text1` and `text1` we'll get the following:

    set.index(text1) # => 0
    set.index(text2) # => 0

This is due to `Array#index` comparing objects using `Object#==`. This can be
worked around as following:

    def index(node)
      @nodes.each_with_index do |current, index|
        return index if node.equal?(current)
      end

      return
    end

The next problem is that NodeSet relies on `Array#include?` in a bunch of
places, and this method _also_ relies on `Object#==` (basically any method
searching for values in an Array uses `#==`). This behaviour will in turn break
code such as `Node#next_element` (which uses `NodeSet#index` to find the index
of `self`).

Because there can be a lot of other cases where usage of a custom `#==` breaks
things I've decided to scrap this feature. It's too risky to implement compared
to the (in my opinion) little benefit it brings.
