### ISSUE TITLE
What is &nbsp; replaced with?

### ISSUE THREAD

**Issue by lham** [YorickPeterse/oga#90]
I'm running into a weird problem when parsing elements containing text followed by some `&nbsp;` within my rails project. If I run 

    require 'oga'
    
    doc = Oga.parse_html('<p>hello&nbsp;&nbsp;</p>');
    str = doc.css('p').text;
    
    puts str.inspect
    puts str.strip.inspect
    puts str[/^\s*(.*?)\s*$/, 1].inspect

it gives me the following output

    "hello  "
    "hello  "
    "hello  "

For some reason I'm not able to remove the trailing whitespace using `strip()` or regex. To me it seems like `&nbsp;` is being replaced by something else than whitespace. Not sure if this is due to the gem or if I'm doing something else wrong here...

**Comment by lham** [comment]
Well, some further investigation shows that `&nbsp;` is replaced by `ASCII DEC 160` (which is a non-breaking space and not by `ASCII DEC 32` which is the normal space character. This makes sense when I think about it. 

Some googling gave me http://stackoverflow.com/questions/8653661/cant-split-strip-by-space-in-a-string-in-ruby-because-its-an-nbsp-character which points out why this happens in ruby. To quote:

> \s matches only ASCII spaces, while [[:space:]] will match all unicode spaces

so the solution would be to use `str[/^[[:space:]]*(.*?)[[:space:]]*$/, 1]` instead.

**Comment by Arcovion** [comment]
I get `"hello&nbsp;&nbsp;"` for each of those, what happens if you try `p str.chomp '&nbsp;&nbsp;'`?

**Comment by YorickPeterse** [comment]
@lham As you found yourself, an unbreakable space is not the same as a regular space, thus `String#strip` won't actually remove it. The easiest way to remove it is as following:

    some_string.gsub(/#{Oga::HTML::Entities::DECODE_MAPPING['&nbsp;']}$/, '')

or:

    some_string.gsub(/#{[160].pack('U')}$/, '')

@Arcovion You'll need at least version 0.3.0 for proper HTML/XML entity conversions. The output you're getting looks like something is going wrong with encodings, which might be a separate issue. Either way, the entity conversion code lives under `Oga::XML::Entities` and `Oga::HTML::Entities`. The docs can be found here:

* http://code.yorickpeterse.com/oga/latest/Oga/XML/Entities.html#decode-class_method
* http://code.yorickpeterse.com/oga/latest/Oga/HTML/Entities.html#decode-class_method

**Comment by Arcovion** [comment]
Thx, how about an `encode` method for HTML entities?
My encoding is alright: `?\u00A0 == [160].pack('U')` - it's not a problem with your gem.

**Comment by YorickPeterse** [comment]
> Thx, how about an encode method for HTML entities?

What do you need this for? There's already `Oga::XML::Entities.encode` which can take an entity mapping to use for conversion.

> I think it would be better to use raw strings: "\u222A\uFE00"

Why are you setting `Encoding.default_external` to ASCII? `Array#pack` requires `Encoding.default_external` to be set to UTF8 to work properly when using `pack('U')`.

**Comment by Arcovion** [comment]
Yea I was thinking it wasn't encoding some things:
```ruby
$ irb -r oga
2.2.1 :001 > Oga::XML::Entities.encode '©'
 => "©"
2.2.1 :002 > Oga::HTML::Entities.decode '&nbsp'
 => 
```
But actually it's not needed, [HTMLEntities](https://github.com/threedaymonk/htmlentities) has a way to use named stuff for everything, hexadecimal and other things but that's beyond the scope of this gem:
```ruby
$ irb -r htmlentities
2.2.1 :002 > HTMLEntities.new.encode '©'
 => "©"
2.2.1 :003 > HTMLEntities.new.encode '©', :named
 => "&copy;"
```
Also the decoders behave slightly differently, so I assumed there would be two encoders - probably doesn't matter but from a usability perspective it makes sense I think:
```ruby
$ irb -r oga
2.2.1 :001 > Oga::XML::Entities.decode '&nbsp;'
 => ""
2.2.1 :001 > Oga::HTML::Entities.decode '&nbsp;'
 => " "
```
I'm only using ASCII for clarity, it shouldn't affect the behaviour of anything internally, just how the output is displayed. You get the same character regardless of how you construct the string or display it:
```ruby
$ irb
2.2.1 :001 > "\u222A\uFE00"
 => "∪︀"
```

**Comment by YorickPeterse** [comment]
> Also the decoders behave slightly differently, so I assumed there would be two encoders - probably doesn't matter but from a usability perspective it makes sense I think:

In the first line you're decoding a non existing XML entity, in the second line you're decoding an HTML entity. The entity `&nbsp;` is only defined in HTML, not XML, thus you only get an unbreakable space when using `Oga::HTML::Entities`. There's currently no `Oga::HTML::Entities.encode` because Oga itself has no use case for such a method.

> Note these two are different, the latter is the correct conversion for &cups;. You can't see the difference because I turned off ASCII encoding...

The difference you're seeing here is because while Oga uses `[8746, 65024].pack('U')` this doesn't actually produce a string that uses the exact same input codepoints:

    [8746, 65024].pack('U').codepoints # => [8746]

As a result `Oga::HTML::Entities::DECODE_MAPPING['&cups;']` will not be the same as `"\u222A\uFE00"`. I'm not sure why this is the case, but it's not something I can do much about other than replacing all `Array#pack` calls (which I'd rather not do unless absolutely necessary).

**Comment by Arcovion** [comment]
> There's currently no Oga::HTML::Entities.encode because Oga itself has no use case for such a method.

It would be nice to have this though, Oga could be both a HTML/XML parser and an entity converter. I just think it would be a useful utility, for example the HTMLEntities gem isn't able to decode `&cups;` but your gem can - just add `Oga::HTML::Entities.encode` and you have a full converter.

> Oga uses `[8746, 65024].pack('U')` this doesn't actually produce a string that uses the exact same input codepoints

This is a bug, no? You can fix it with `U*` instead of `U` for all of the entities.
Using pack is expensive compared to the other two ways I mentioned though, I think it's worth changing them. I can put together a PR to change them all to UTF-8 or ASCII strings, what do you think?

**Comment by YorickPeterse** [comment]
>  I just think it would be a useful utility, for example the HTMLEntities gem isn't able to decode &cups; but your gem can - just add Oga::HTML::Entities.encode and you have a full converter!

Oga isn't an HTML/XML entity conversion Gem, it just happens to have it because it's required by the XML/HTML specifications. I don't feel comfortable adding something Oga itself will never use. This method isn't needed because only a few special characters have to be encoded back to entities when generating XML (e.g. `<` has to become `&lt;` but `©` is perfectly valid as is).

> This is a bug, no? You can fix it with U* instead of U for all of the entities.

Ah, then at least that should be easy to fix.

> Using pack is expensive compared to the other two ways I mentioned though, I think it's worth changing them. I can put together a PR to change them all to UTF-8 or ASCII strings, what do you think?

This depends on the definition of "slow". The file containing these pack calls is loaded upon Gem load, not during runtime. The overhead added to the bootup process is fairly minor too:

```
oga $ time ruby -e ''

real    0m0.079s
user    0m0.067s
sys     0m0.010s
oga $ time ruby -e ''

real    0m0.077s
user    0m0.080s
sys     0m0.000s
oga $ time ruby -e ''

real    0m0.076s
user    0m0.060s
sys     0m0.013s
oga $ time ruby -r ./lib/oga/html/entities.rb -e ''

real    0m0.097s
user    0m0.083s
sys     0m0.010s
oga $ time ruby -r ./lib/oga/html/entities.rb -e ''

real    0m0.099s
user    0m0.080s
sys     0m0.017s
oga $ time ruby -r ./lib/oga/html/entities.rb -e ''

real    0m0.099s
user    0m0.090s
sys     0m0.010s
```

So just loading that file adds about 20 ms. I'd much rather optimize the XPath evaluator or other parts than to shave of a few milliseconds that won't even affect your runtime. The list of entities isn't going to get bigger anytime soon either, so it's not like it one day will be exponentially slower than today.
